
tools_list = list(
    set(
        [
            ".NET",
            "Adobe XD",
            "Airflow",
            "Alamofire",
            "Alexa Skills Kit",
            "Amplify",
            "Ansible",
            "Apache",
            "Apache Kafka",
            "Apache Airflow",
            "Apache Nifi",
            "Apache NiFi",
            "Apache Storm",
            "AppDynamics",
            "Argo",
            "Asana",
            "Athena",
            "AWS",
            "AWS SageMaker",
            "Azure",
            "Azure DevOps",
            "Azure ML",
            "Bash",
            "BigQuery",
            "Bizagi",
            "Bitbucket",
            "Blender",
            "Bootstrap",
            "C++",
            "Caffe",
            "Cassandra",
            "Chef",
            "Cisco ASA",
            "Cisco Packet Tracer",
            "CircleCI",
            "ClickHouse",
            "CloudFormation",
            "CloudWatch",
            "Combine",
            "Confluence",
            "CoreData",
            "CSS",
            "Dagger",
            "DataRobot",
            "Databricks",
            "Datadog",
            "dbt (data build tool)",
            "Django",
            "Docker",
            "Docker Swarm",
            "Domo",
            "Draw.io",
            "Dynatrace",
            "Eclipse",
            "ElasticSearch",
            "Excel",
            "Fargate",
            "FastAPI",
            "Firebase",
            "Figma",
            "Flask",
            "GCP",
            "Git",
            "GitHub",
            "GitLab CI/CD",
            "Glide",
            "Golang",
            "Google AI Platform",
            "Google Analytics",
            "Google Tag Manager",
            "Gradle",
            "Grafana",
            "Graylog",
            "H2O.ai",
            "Hadoop",
            "Helm",
            "Heroku",
            "HubSpot",
            "Hugging Face",
            "IIS",
            "Informatica",
            "Informatica Cloud",
            "Insomnia",
            "IntelliJ IDEA",
            "iOS SDK",
            "Jenkins",
            "Jenkins X",
            "JIRA",
            "JMeter",
            "Jupyter",
            "Jupyter Notebook",
            "JUnit",
            "Kali Linux",
            "Keras",
            "Kibana",
            "KNIME",
            "Kotlin",
            "Kubernetes",
            "Lambda",
            "Linux",
            "Logstash",
            "Looker",
            "LookML",
            "Lucidchart",
            "MATLAB",
            "Marketo",
            "Maven",
            "Metasploit",
            "Microsoft Cognitive Services",
            "Microsoft Project",
            "Minitab",
            "MongoDB",
            "MongoDB Atlas",
            "Mocha",
            "Mulesoft",
            "Nagios",
            "Netlify",
            "New Relic",
            "Nexus",
            "Nginx",
            "Node.js",
            "Notion",
            "NumPy",
            "Objective-C",
            "OpenCV",
            "OpenShift",
            "OpenStack",
            "Oracle",
            "Oracle Cloud",
            "Oracle EBS",
            "Pandas",
            "Palo Alto Networks",
            "PeopleSoft",
            "Podman",
            "PostgreSQL",
            "Power BI",
            "Power Automate",
            "PowerApps",
            "PowerShell",
            "Presto",
            "Prometheus",
            "Puppet",
            "PyCharm",
            "Python",
            "Pytest",
            "PyTorch",
            "QlikView",
            "Qlik Sense",
            "R",
            "R Programming",
            "R Studio",
            "Rancher",
            "RapidMiner",
            "React",
            "Red Hat Enterprise Linux",
            "Redshift",
            "Retrofit",
            "Ruby",
            "RxJava",
            "Salesforce",
            "SAP",
            "SAP Analytics Cloud",
            "Scala",
            "Scikit-learn",
            "SciPy",
            "Selenium",
            "Snyk",
            "Snowflake",
            "Spark",
            "Splunk",
            "Spyder",
            "SQLite",
            "SSH",
            "SQL",
            "SSL",
            "Stata",
            "Superset",
            "Swagger",
            "Swift",
            "Tableau",
            "Tableau Prep",
            "Tailwind CSS",
            "Talend",
            "TensorFlow",
            "Terraform",
            "Trello",
            "Travis CI",
            "Unity",
            "Unreal Engine",
            "Vercel",
            "Visual Studio",
            "VS Code",
            "Vue.js",
            "Wireshark",
            "Windows Server",
            "Xcode",
            "C#",
            "ASP.NET",
            "Java",
            "Spring",
            "JavaScript",
            "Angular",
            "Ruby on Rails",
            "PHP",
            "Laravel",
            "Gin",
            "Qt",
            "SwiftUI",
            "Kotlin",
            "Android SDK",
            "TypeScript",
            "NestJS",
            "Shiny",
            "Scala",
            "Play",
            "Elixir",
            "Phoenix",
            "Clojure",
            "Compojure",
            "Rust",
            "Rocket",
            "Dart",
            "Flutter",
            "Haskell",
            "Yesod",
            "Julia",
            "HTTP.jl",
            "Lua",
            "LÖVE",
            "Shell",
            "PowerShell",
            "Cocoa",
            "Simulink",
            "Assembly",
            "NASM",
            "COBOL",
            "OpenCOBOL",
            "Pascal",
            "Free Pascal",
            "F#",
            "ASP.NET Core",
            "Blazor",
            "Visual Basic .NET",
            "Windows Forms",
            "Delphi",
            "Lazarus",
            "ActionScript",
            "Flex",
            "Groovy",
            "Grails",
            "VBScript",
            "ASP Classic",
            "Smalltalk",
            "Pharo",
            "Scheme",
            "Racket",
            "Prolog",
            "SWI-Prolog",
            "Ada",
            "GNAT",
            "Nim",
            "Nimble",
            "Crystal",
            "Lucky",
            "Solidity",
            "Truffle",
            "V",
            "Vlang",
            "Hibernate",
            "Sinatra",
            "Echo",
            "Vapor",
            "Ktor",
            "Symfony",
            "Actix",
            "Aqueduct",
            "Nerves",
            "Play Framework",
            "Giraffe",
            "SSRS",
            "Google Data Studio",
            "Mode Analytics",
            "IBM Cognos Analytics",
            "Azure Data Factory (ADF)",
            "SSIS",
            "Matillion",
            "Kafka Connect",
            "PowerBI",
            "VBA",
        ]
    )
)
